### PR TITLE
add go.mod

### PR DESCRIPTION
**Pull request by tmm1**
simple `go mod init`

### CODE REVIEW

**Comment by mattrobenolt** [comment]
What’s this needed for if we don’t use any dependencies ourselves?

**Comment by tmm1** [comment]
It makes it easier to develop, as you can simply check this repo out anywhere, make changes and run tests. Without the go.mod file you have to clone it into your GOPATH

**Comment by mattrobenolt** [comment]
Ah, cool. TIL. 

Then last question: since this specifies go 1.13, what does that mean for running it with less than that?

**Comment by tmm1** [comment]
Good question. I'm not certain- it might print a warning but I don't think it has any real impact.

**Comment by mattrobenolt** [comment]
If I had to guess, it’d be a flag for minimum version compatibility. I’d vote we put it to go 1.12, since that’s the first version for go modules. And we don’t do anything that’d require 1.13.

**Comment by tmm1** [comment]
> I’d vote we put it to go 1.12

done.

**Comment by mattrobenolt** [comment]
Cool, and thanks for the explanation. :)

**Pull request merged**
