### PR TITLE
Travis-CI: initial configuration

### PR DESCRIPTION
**Pull request by dolmen**
Configuration for https://travis-ci.org/certifi/gocertifi

### CODE REVIEW

**Comment by dolmen** [comment]
Rebased on master and add go 1.12.x.

**Comment by tmm1** [comment]
:+1:

**Comment by tmm1** [comment]
@mattrobenolt could you merge this?

**Comment by tmm1** [comment]
I guess you also have to visit https://travis-ci.org/ and enable it there for this repo.

**Comment by mattrobenolt** [comment]
It appears I do not have sufficient permissions in Travis to enable this. 

/cc @Lukasa maybe?

**Pull request merged**
