### PR TITLE
Split certs into a separate file

### PR DESCRIPTION
**Pull request by eclipseo**
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Why? This now incurs overhead of reading another file at runtime, and is there any guarantee on where this file will be on the filesystem when someone installs this package with `go get` ? I'm really a -1 here unless there's some substantial benefit.

**Comment by eclipseo** [comment]
In packaging for a Linux distro, we are patching out the bundled certs to use the system ones. In order to avoid making a new patch for every time the certs change, it would be useful to separate it into its own file.

**Comment by mattrobenolt** [comment]
Do you know how this would work as a Go module with this additional data file? afaik this won't be easy to manage. Since it's now a file that must exist outside of your Go program after it's compiled.

In your use case as well, I don't even know how that'd be applicable since at runtime, this is compiled into a program, and not loaded from disk. This change would mean that a compiled Go program would also need to include additional data files.

The reason this exists is for situations when a system level certificate is not available, typically used by programs running within tiny docker containers, etc.

This change fundamentally breaks this behavior in a very drastic way and I'm not sure how this affects Linux packaging tbh.

**Comment by mattrobenolt** [comment]
If we needed to do this, there'd have to be an environment variable to set the path on the file system to load certificates from instead. I'd be more open for say, checking this environment variable, if it exists, load them, if not, fall back to the bundled certs. But as-is, I'm fairly confident this is a 100% breaking change for no value.

**Comment by eclipseo** [comment]
Ok no problem.

**Pull request closed without merging**
